global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
        - 'host.docker.internal:8081'  # Transaction Ingestor
        - 'host.docker.internal:8082'  # Feature Extractor
        - 'host.docker.internal:8083'  # Rule Engine
        labels:
          application: 'sentinelpay'
