spring:
  application:
    name: rule-engine

  # DATABASE (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:15432/rule_engine_db
    username: sentinel
    password: sentinel123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
