server:
  port: 8081

spring:
  application:
    name: transaction-ingestor
  cloud:
    discovery:
      enabled: false

  profiles:
    active: kafka
    # active: noop
  
  # DATABASE (PostgreSQL)
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/${DB_NAME:transaction_ingestor_db}
    username: ${DB_USER:sentinel}
    password: ${DB_PASSWORD:sentinel123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update  # Creates tables automatically
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # KAFKA
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
      client.listener.name: PLAINTEXT_HOST
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

event:
  publisher: kafka

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
