server:
  port: 8082

spring:
  application:
    name: feature-extractor
  cloud:
    discovery:
      enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/${DB_NAME:feature_extract_db}
    username: ${DB_USER:sentinel}
    password: ${DB_PASSWORD:sentinel123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    consumer:
      group-id: feature-extractor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        client.listener.name: PLAINTEXT_HOST
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:16379}

account:
  service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8087}


eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
