version: '3.8'
services:
  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sentinelpay
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel123
    ports: ["15432:5432"]  
    # volumes: [postgres_data:/var/lib/postgresql/data]
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Cache
  redis:
    image: redis:7-alpine
    ports: ["16379:6379"]  

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports: ["22181:2181"]  

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: [zookeeper]
    ports: ["19092:19092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 20

  fraud-ml-service:
    build:
      context: ../microservices/ml-services/fraud-ml-service
    depends_on:
      kafka:
        condition: service_healthy
    ports: ["18091:8091"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      INPUT_TOPIC: transactions.enriched
      OUTPUT_TOPIC: fraud.ml
      KAFKA_GROUP_ID: fraud-ml-service
      MODEL_VERSION: logreg-synthetic-v3
      HEALTH_PORT: 8091
    restart: unless-stopped

volumes:
  postgres_data:
